# Created by Jekyll Writer
title: Finale
email: tao@yeket.com
description: Write an awesome description for your new site here
baseurl: /blog
url: ''
permalink: '/:year/:month/:day/:title/'
twitter_username: csdww
github_username: yeket
markdown: kramdown
